name: Codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 15.13.28  # It is recommended to specify specifying version range
        # for semantic-release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
